"""phase3_publishing_analytics

Revision ID: 40c532181d4c
Revises: f28edb1c473c
Create Date: 2026-04-15 12:57:19.921614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40c532181d4c'
down_revision: Union[str, None] = 'f28edb1c473c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('published_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('network', sa.String(length=50), nullable=False),
    sa.Column('network_post_id', sa.String(length=500), nullable=True),
    sa.Column('utm_params', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('published_post_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('utm_source', sa.String(length=255), nullable=True),
    sa.Column('utm_medium', sa.String(length=255), nullable=True),
    sa.Column('utm_campaign', sa.String(length=255), nullable=True),
    sa.Column('utm_content', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['published_post_id'], ['published_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('published_post_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['published_post_id'], ['published_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('approval_requests', 'decision',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('approved', 'rejected', name='approvaldecision'),
               existing_nullable=True)
    op.add_column('social_accounts', sa.Column('credentials', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_accounts', 'credentials')
    op.alter_column('approval_requests', 'decision',
               existing_type=sa.Enum('approved', 'rejected', name='approvaldecision'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_table('post_metrics')
    op.drop_table('lead_events')
    op.drop_table('published_posts')
    # ### end Alembic commands ###
